node () {
    def commit_id
    stage('Getting Source code') {

        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"                        
        commit_id = readFile('.git/commit-id').trim()
   }
    stage('test') {
        echo "Test Completed"
        nodejs(nodeJSInstallationName: 'nodejs') {
    
            sh 'npm install --only=dev'
            sh 'npm test'
            
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'testdockerregistry') {
       def app = docker.build("bootcamp-starter-kit_posts-api:${commit_id}", '.').push()
     } 
   }
}