node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir ('nodejs-pipeline-test') {
          sh 'npm install --only=dev'
          sh 'npm test'
     }
     }
   }
   stage('Building Test App') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir ('nodejs-pipeline-test') {
          sh 'npm install'
     }
     }
   }
   stage('docker build/push') {
     dir ('nodejs-pipeline-test') {
       docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
        def app = docker.build("luckychinedum/nodejs-pipeline:${commit_id}", '.').push()
     }
     }
   }
}
