apiVersion: apps/v1
kind: Deployment
metadata:
    name: post-api
    labels:
        app: post-api
    namespace: hopper
spec:
    replicas: 1
    selector:
        matchLabels:
            app: post-api
    template:
        metadata:
            labels:
                app: post-api
        spec:
            containers:
                - name: post-api-service
                  image: bootcamp-starter-kit_posts-api:latest
                  imagePullPolicy: Never
                  ports:
                     - containerPort: 8000
                  env:
                      - name: PG_HOST
                        value: postgres-service
                      - name: PG_PORT
                        value: "5432" 
                      - name: PG_DATABASE
                        value: starterkit
                      - name: POSTGRES_USER
                        valueFrom:
                          secretKeyRef:
                            name: postgres-db
                            key: username
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: postgres-db
                            key: password
 
